apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/prometheus-default: "true"
        io.kompose.service: alertmanager
    spec:
      containers:
        - image: quay.io/prometheus/alertmanager
          name: alertmanager
          ports:
            - containerPort: 9093
          resources: {}
      restartPolicy: Always
status: {}
