apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: fake-prometheus-data
  name: fake-prometheus-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fake-prometheus-data
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/prometheus-default: "true"
        io.kompose.service: fake-prometheus-data
    spec:
      containers:
        - env:
            - name: FD_DATASOURCE
              value: prom
          image: grafana/fake-data-gen
          name: fake-prometheus-data
          ports:
            - containerPort: 9091
          resources: {}
      restartPolicy: Always
status: {}
