apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prometheus-random-data
  name: prometheus-random-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus-random-data
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/prometheus-default: "true"
        io.kompose.service: prometheus-random-data
    spec:
      containers:
        - image: prometheus-random-data
          name: prometheus-random-data
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
