apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-sample
spec:
  version: 8.6.1
  count: 1
  elasticsearchRef:
    name: "elasticsearch-sample"
  http:
   service:
     spec:
       type: LoadBalancer
       loadBalancerIP: 35.222.0.200
      #  ports:
      #     - name: "5601"
      #       port: 80
      #       targetPort: 5601
  # this shows how to customize the Kibana pod
  # with labels and resource limits
  podTemplate:
    metadata:
      labels:
        foo: bar
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 1Gi
            cpu: 1
  # http:
  # service:
  #   spec:
  #     # expose this cluster Service with a LoadBalancer
  #     type: LoadBalancer