apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: graphite11
  name: graphite11
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: graphite11
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/graphite-default: "true"
        io.kompose.service: graphite11
    spec:
      containers:
        - image: graphiteapp/graphite-statsd
          name: graphite11
          ports:
            - containerPort: 80
            - containerPort: 2003
            - containerPort: 2004
            - containerPort: 2023
            - containerPort: 2024
          resources: {}
      restartPolicy: Always
status: {}
