apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: graphite11
  name: graphite11
spec:
  ports:
    - name: "8180"
      port: 8180
      targetPort: 80
    - name: "2103"
      port: 2103
      targetPort: 2003
    - name: "2104"
      port: 2104
      targetPort: 2004
    - name: "2123"
      port: 2123
      targetPort: 2023
    - name: "2124"
      port: 2124
      targetPort: 2024
  selector:
    io.kompose.service: graphite11
status:
  loadBalancer: {}
