apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: promtail
  name: promtail
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promtail
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/jaeger-default: "true"
        io.kompose.service: promtail
    spec:
      containers:
        - args:
            - -config.file=/etc/promtail/docker-config.yaml
          image: grafana/promtail:master
          name: promtail
          resources: {}
          volumeMounts:
            - mountPath: /etc/promtail/docker-config.yaml
              name: promtail-claim0
            - mountPath: /var/log
              name: promtail-claim1
            - mountPath: /var/log/grafana
              name: promtail-claim2
      restartPolicy: Always
      volumes:
        - name: promtail-claim0
          persistentVolumeClaim:
            claimName: promtail-claim0
        - name: promtail-claim1
          persistentVolumeClaim:
            claimName: promtail-claim1
        - name: promtail-claim2
          persistentVolumeClaim:
            claimName: promtail-claim2
status: {}
